var irish_names_female = [
    'Adele','Áedammair','Affraic','Aibhilín','Aíbhinn','Aíbinn','Aifric','Ailbhe','Aili','Áilís','Áine',
    'Aislin','Aisling','Aislinn','Aithche','Albina','Amber','Anlaith','Aodhamair','Aodhnait','Aoibheann',
    'Aoibhin','Aoibhinn','Aoife','Aoileann','Ardis','Athracht',
    'Barrdhubh','Bé Fáil','Bean Mhídhe','Bébhinn','Bébinn','Ben Muman','Bláithín','Bláth','Bláthnaid (dim.)',
    'Blinne','Brenda','Bríd','Bridget','Brídín (dim.)','Brighdín (dim.)','Brighid','Brónach','Bryna',
    'Buadhnait','Buanait',
    'Cacht','Caelan','Cainnech','Caitlin','Caitlín','Caitrín','Caitríona','Caoilfhionn','Caoimhe','Carman',
    'Caroline','Casey','Cassidy','Cathleen','Catraoine','Catriona','Catríona','Charlotte','Chloe','Ciamhnait',
    'Ciannait','Ciara','Cliodhna','Clíona','Clodagh','Cobhfhlaith','Cobhlaith','Colleen','Condal','Crínóc',
    'Crystal','Cumman',
    'Dailfind','Damhnait','Danielle','Daphne','Darerca','Dearbháil','Dearbhfhorgaill','Dearbhfhorghaill',
    'Dearbhla','Deidre','Deirbhile','Deirdre','Derbforgaill','Dervla','Diana','Dianaimh','Doireann','Dub Lémna',
    'Dubh Essa','Dubh Themrach','Dubhchobhlaigh','Dubhóg','Dúnlaith',
    'Éabha','Earlene','Earnait','Easnadh','Edna','Éibhleann','Eibhlin','Eibhlín','Eibhlinn','Eibhlínn','Eileen',
    'Eilín','Eilís','Eilish','Eimear','Eimer','Eimhear','Éimhear','Eimhir','Eithne','Elec','Émer','Erin','Étaín',
    'Faoiltighearna','Fedelm','Feidhelm','Féthnaid','Féthnat','Fiadh','Fiadhnait','Fidelma','Finbil','Fíne',
    'Fíneamhain','Fíona','Fionnabhair','Fionnghuala','Fionnuala','Flann','Flannait','Fodhla','Forbflaith','Forbhlaith',
    'Forlaith',
    'Geiléis','Gelgéis','Gemma','Georgia','Gnathnad','Gobnait','Gormfhlaith','Gormflaith','Gormlaith','Grace',
    'Gráinne',
    'Harper','Heather','Helena','Holly',
    'Íde','Imelda','Iodhnait','Ionait',
    'Jacqueline','Jacqui',
    'Karen','Kathleen','Keira',
    'Lann','Lasairfhíona','Lathir','Lerben','Lerthan','Lí Ban','Lígach',
    'Máel Muire','Maeve','Máire','Mairead','Mairéad','Mairghréad','Máirín','Mary','Maura','Maureen','Meabh',
    'Meadhbh','Mealla','Medb','Meibhín (dim.)','Meidhbhín (dim.)','Melanie','Míde','Miodhnait','Míonait',
    'Modwenna','Móirín','Moncha','Moninne','Mór','Mór Muman','Muadhnait','Muire','Muireann','Muirenn','Muirgheal',
    'Muirinn','Muirne',
    'Nadia','Natalia','Neasa','Niamh','Nóirín','Nollaig','Nora','Nóra','Nuala',
    'Odharnait','Onóra','Órfhlaith','Órla','Órlaith','Órnait',
    'Pádraigín','Patricia','Pegeen','Peig','Peigi','Peigín','Petunia',
    'Raghnailt','Ráichéal','Rathnait','Ríoghnach','Ríona','Ríonach','Róis','Róise','Róisín','Rós','Rosaleen',
    'Sadb','Sadhbh','Samthann','Saoirse','Saorfhlaith','Saorla','Saorlaith','Sebdann','Sétach','Shauna','Sheila',
    'Sibéal','Síle','Sinéad','Sinech','Siobhan','Siobhán','Síobhra','Siofra','Síofra','Sisuile','Síthmaith',
    'Sláine','Sorcha',
    'Táethen','Taileflaith','Tara','Tómnat','Tuathflaith','Tuathla','Tuathlaith',
    'Uainionn','Uallach','Uasal','Úna',
    'Valerie','Veronica'
]

var irish_names_male = [
    'Abbán','Abraham','Adam','Adhamh','Aengus','Agaistín','Ágastas','Aibhne','Aidan','Ailbhe','Ailill',
    'Ailin','Ailín','Aindréas','Aindriú','Ainníleas','Alexander','Alistair','Ambrós','Amhalgaidh','Amhlaoibh',
    'Angus','Anluan','Anmchadh','Antóin(e)','Aodh','Aodhagán','Aodhán','Aogán','Aonghus','Ardghal','Árdghal',
    'Ardghar','Árón','Art','Arthur','Artúr','Aulay',
    'Bairre','Baothghalach','Barra','Beacán','Bearach','Bearchán','Bearnárd','Beinidict','Bran','Bréanainn',
    'Breandán','Breanndán','Breasal','Brendan','Brian','Brochadh','Bruno','Buadhach',
    'Caden','Cailean','Cainneach','Cairbre','Calbhach','Calvin','Canice','Caoimhghín','Caoimhín','Caolán',
    'Caomhán','Carraig','Cárthach','Casey','Cathal','Cathaoir','Cathbharr','Ceallach','Ceallachán','Cearbhall',
    'Christian','Christy','Cian','Cianán','Ciarán','Cillian','Cinnéididh','Cinnéidigh','Cionaodh','Ciothruadh',
    'Coilean','Coileán','Coilín','Coinneach','Coireall','Colin','Colla','Colm','Colman','Colmán','Colum',
    'Comán','Comhghall','Comhghan','Conaire','Conal','Conall','Conán','Conchobar','Conchobhar','Conchubhar',
    'Conchúr','Conghalach','Conle','Conmhac','Conn','Connla','Connlaodh','Connor','Conor','Conway','Cormac',
    'Cosnamhach','Crimthann','Criomthann','Críostóir','Cróchán','Crónán','Cuan','Cúchonnacht','Cuileán',
    'Cuimín','Cúmhaighe','Cúmheadha',
    'Dabhag','Dabhóg','Daibhí','Dainéal','Dáire','Dáithí','Damháin','Dara','Darragh','Deaglán','Déaglán',
    'Deasmhumhnach','Declan','Diarmaid','Diarmait','Dirk','Domhnall','Don','Dónall','Donn','Donnacha','Donnán (dim.)',
    'Donnchadh','Donnchadha','Donnghaile','Dougal','Dubhaltach','Dubhán','Dubhghall','Dubhghlas','Dúnlang',
    'Eachaidh','Eachann','Eachdhonn','Eachmarcach','Eachthighearn','Éadbhárd','Eamon','Éamon','Eamonn',
    'Éamonn','Éanán','Éanna','Earcán','Earnán','Éibhear','Eignach','Éignach','Eigneachán','Éigneachán',
    'Éimhín','Éinde','Eireamhán','Eireamhón','Éireamhón','Eirnín','Enda','Eochaid','Eochaidh','Eógan','Eoghainín (dim.)',
    'Eoghan','Eoin','Eóin','Euan','Ewan',
    'Fachtna','Fáilbhe','Faolán','Fearadhach','Fearchar','Feardorcha','Fearganainm','Fearghal','Fearghus',
    'Feargus','Feichín','Feidhlim','Féilim','Felix','Fergal','Fergus','Fiach','Fiacha','Fiachna','Fiachra',
    'Finghin','Finn','Finnian','Fionghuine','Fionn','Fionnbharr','Fionntán (dim.)','Fitheal','Flann','Flannán (dim.)',
    'Florence','Fothad','Francie','Froinsias',
    'Garbhán','Gearóid','Gerald','Giolla Críost','Glaisne','Gofraid','Greagoir','Gréagóir',
    'Harold','Heber',
    'Ian','Iarfhlaith','Iarlaith','Íomhar','Íosac','Iósaf','Ióseph','Irial','Iúdás','Ivan',
    'Jack','Jacob','Jarlath','John','Jonathan',
    'Keenan','Kennedy','Kevin','Kian','Killian',
    'Labhrás','Lachtna','Laoighseach','Laoiseach','Lasairian','Liam','Lochlainn','Lochlann','Lomán','Lonán',
    'Lorcán','Loughlin','Lubhrás','Lugaid','Lughaidh',
    'Macdara','Máel Brigte','Maeleachlainn','Maelíosa','Maelsheachlainn','Mainchín','Máirtín','Maitiú','Maodhóg',
    'Maoilín','Maoilir','Maolcholm','Maolcholuim','Maolmhuire','Maolmórdha','Maolruadháin','Marcus','Matha',
    'Mathghamhain','Matthew','Micheal','Mícheál','Mo Lua','Muircheartach','Muirchertach','Muireach','Muireadhach',
    'Muiredach','Muirgheas','Muiris','Murchadh','Murdoch',
    'Naomhán','Naos','Neachtan','Neasán','Neil','Nevan','Niall','Niallán (dim.)','Nioclás','Noel','Nollaig',
    'Odhrán','Oilibhéar','Oireachtach','Oisin','Oisín','Orin','Oscar','Ossian',
    'Pádraig','Patrick','Patsy','Pauric','Peadar','Philip','Póil','Pól','Proinsias',
    'Raibhilín','Ralph','Raonall','Réamann','Réamonn','Riain','Risteárd','Ristéard','Robert','Roibeard','Roibeárd',
    'Roibéard','Roibhilín','Rónán','Ros','Ruadhán','Ruaidhri','Ruairi','Ruairí','Ruari','Ruarí','Ruaridh',
    'Ruibhilín','Ryan',
    'Saerbhreathach','Samuel','Seachnasach','Séadna','Séafra','Séamas','Séamus','Sean','Seán','Séan','Séaonin',
    'Searbhreathach','Seárlas','Seathan','Sechnassach','Senán','Seoirse','Seosamh','Seumas','Shane','Siadhal',
    'Siaghal','Sioda','Síomón','Somhairle','Sorley','Stíofán','Suibhne',
    'Tadhg','Taichleach','Tárlach','Téodóir','Thomas','Tiarnach','Tiarnán','Tighearnán','Tighernach','Tiobóid',
    'Toirdelbach','Toirdhealbhach','Toirleach','Tomás','Torna','Traolach','Treabhair','Trevor','Tristan','Tuathal',
    'Uaitéar','Uaithne','Ualgharg','Uilleac','Uilleag','Uilliam','Uinseann','Ulick','Ultán'
]

var irish_surnames = [
    'Ahearn','Ahern',
    'Barry','Bean Mhic Alasdair','Bean Mhic Alastair','Bean Mhic Alastruim','Bean Mhic Alsandair','Bean Mhic Amhalaí',
    'Bean Mhic Amhalaidh','Bean Mhic Amhalghadha','Bean Mhic Amhalghaidh','Bean Mhic Amhlaoibh','Bean Mhic Coitir',
    'Bean Mhic Íomhair','Bean Mhic Leóid','Bean Mhic Oitir','Bean Mhic Ospaic','Bean Mhic Raghnaill','Bean Mhic Rághnaill',
    'Bean Mhic Raonaill','Bean Mhic Shitric','Bean Mhic Somhairle','Bean Mhig Amhalghadha','Bean Mhig Amhalghaidh',
    'Bean Mhig Íomhair','Bean Mhig Shitric','Bean Uí Arailt','Bean Uí Thomhnair','Bean Uí Thomhnra','Bean Uí Thomhrair',
    'Bean Uí Thormadha','Bean Uí Thormaigh','Beattie','Behan','Bergin','Bermingham','Bowell','Bowie','Bowles',
    'Boyle','Brady','Branagan','Breathnach','Brennan','Breslin','Brian','Broderick','Brophy','Buckley','Bunster',
    'Burke','Burns','Butler','Byrne',
    'Cafferty','Cahill','Callahan','Calleary','Calnan','Canavan','Cannon','Cantwell','Caomhánach','Carew',
    'Carey','Carney','Carroll','Casey','Cassidy','Cavanagh','Clancy','Clare','Clarke','Clooney','Cochrane',
    'Coen','Coffey','Coghlan','Cohan','Colbert','Coleman','Colgan','Collins','Colton','Colum','Comey','Condon',
    'Conlee','Conley','Conly','Connachta','Conneely','Connellan','Connelly','Connery','Connolly','Connor',
    'Conroy','Considine','Cooney','Corcoran','Corrigan','Costello','Coughlan','Cowley','Coyne','Craig','Crean',
    'Cregg','Crosby','Crowley','Cryan','Cullen','Cullinane','Cunneen','Curran','Curry','Cusack',
    'Dál gCais','Dál Messin Corb','Daley','Dargan','Darragh','Davoren','De Barry','De Lacy','Deasy','Degan',
    'Delaney','Dempsey','Dennehy','Devaney','Devaughn','Devine','Devlin','Dickin','Dillon','Dineen','Dinn',
    'Docherty','Doherty','Dolan','Donegan','Dongan','Donlevy','Donnellan','Donnelly','Donohoe','Donohue',
    'Donough','Donovan','Doohan','Doolan','Dooley','Doran','Dougher','Dowdall','Dowling','Downer','Downey',
    'Doyle','Drennan','Duff','Duffy','Dugan','Duignan','Dunne',
    'Enright','Eóganachta‎',
    'Fahey','Fahie','Fahy','Fallon','Fanning','Farley','Farrell','Fay','Fee','Fergus','Ferriter','Fey','Finegan',
    'Finn','Finnegan','Finneran','Finnerty','FitzGerald','Fitzgibbon','FitzPatrick','Fitzpatrick','Flanagan',
    'Flannery','Flinn','Flynn','Fogarty','Fogerty','Folan','Foley','Forbes','Forrestal','Freyne','Friel',
    'Gaffey','Gaffney','Gahan','Gallacher','Gallagher','Garry','Garvey','Gaughan','Gawley','Geaney','Getty',
    'Gettys','Giles','Gillen','Gleeson','Godfrey','Gordon','Gormley','Grady','Greaney','Grennan','Griffin',
    'Guilfoil',
    'Hagarty','Halligan','Hallissey','Hamill','Hammill','Hampson','Hannan','Hanrahan','Hardiman','Hassan','Hastings',
    'Haughey','Haughn','Haughney','Healey','Heaney','Hegarty','Hennessey','Hennessy','Hennigan','Heron','Hession',
    'Hewson','Hickey','Higgins','Hiney','Hoey','Hogan','Holland','Honan','Hoobin','Horan','Hoy','Hughes','Hurley',
    'Irwin',
    'Jennings',
    'Kavanagh','Kearney','Keefe','Kehoe','Keldon','Kelleher','Keller','Kelly','Kennedy','Kenniff','Kenny',
    'Keogh','Keough','Kerwin','Kiely','Kiggins','Killeen','Killoran','Kimmins','Kimmons','King','Kinlen','Kinsella',
    'Kissane','Knowles','Koglin',
    'Lally','Lalor','Lane','Larkin','Laughlin','Laverty','Leamy','Lee','Lenihan','Lennon','Lohan','Loughlin',
    'Lucey','Lynam','Lynch',
    'Mac Alasdair','Mac Alastair','Mac Alastruim','Mac Alsandair','Mac Amhalaí','Mac Amhalaidh','Mac Amhalghadha',
    'Mac Amhalghaidh','Mac Amhlaoibh','Mac an Bhaird','Mac an Iomaire','Mac Aodhagáin','Mac Brádaigh','Mac Cába',
    'Mac Cathmhaoil','Mac Cearbhaill','Mac Coitir','Mac Con Iomaire','Mac Con Midhe','Mac Críodáin','Mac Diarmada',
    'Mac Eacháin','Mac Eoin','Mac Eoin Bissett family','Mac Fhirbhisigh','Mac Fhlannchaidh','Mac Gafraidh',
    'Mac Giolla Chuda','Mac Giolla Mhochuda','Mac Giolla Phádraig dynasty','Mac Giolla Seanáin','Mac ind Óclaich',
    'Mac Íomhair','Mac Leóid','Mac Lochlainn','Mac Maoláin','Mac Murchadha','Mac Oitir','Mac Ospaic','Mac Raghnaill',
    'Mac Rághnaill','Mac Raonaill','Mac Ruaidhrí','Mac Scannláin','Mac Sitric','Mac Siúrtáin','Mac Somhairle',
    'Mac Suibhne','Mac Torcaill','MacCarthy','MacCraith','MacDermot','MacDowell','MacGaffin','MacGahan','MacGorman',
    'MacLeod','MacManus','MacMorrough Kavanagh','MacNamara','MacShane','Mag Amhalghadha','Mag Amhalghaidh',
    'Mag Íomhair','Mag Máilin','Mag Shitric','Magan','Magee','Magennis','Maguire','Mahon','Mallins','Malloy',
    'Malone','Mangan','Manning','Marley','Marmion','Martyn','McArdle','McAtee','McAuley','McBride','McCabe',
    'McCafferty','McCaffrey','McCamley','McCann','McCartan','McCaughan','McCaughey','McCaul','McCauley','McCausland',
    'McCleary','McClure','McCluskey','McColgan','McCormack','McCormick','McCotter','McCourt','McCracken','McCreary',
    'McCreery','McCrery','McCrory','McDonagh','McDowell','McDuffie','McElroy','McEvoy','McFadden','McGaffin',
    'McGahan','McGarry','McGaughey','McGeachie','McGee','McGettigan','McGowan','McGowen','McGrady','McGrane',
    'McGraw','McGrory','McGuinness','McGurn','McKay','McKee','McKendrick','McKenna','McKeogh','McKeown',
    'McKinley','McLaughlan','McLaughlin','McLoughlin','McMahon','McManaman','McManus','McMenamin','McMillin',
    'McMullen','McNulty','McPhillips','McQuillan','McRory','McSherry','McSorley','Mehigan','Mhic Alasdair',
    'Mhic Alastair','Mhic Alastruim','Mhic Alsandair','Mhic Amhalaí','Mhic Amhalaidh','Mhic Amhalghadha',
    'Mhic Amhalghaidh','Mhic Amhlaoibh','Mhic Coitir','Mhic Íomhair','Mhic Leóid','Mhic Oitir','Mhic Ospaic',
    'Mhic Raghnaill','Mhic Rághnaill','Mhic Raonaill','Mhic Shitric','Mhic Somhairle','Mhig Amhalghadha',
    'Mhig Amhalghaidh','Mhig Íomhair','Mhig Shitric','Milligan','Minogue','Mitchell','Molloy','Monaghan',
    'Monahan','Mooney','Moore','Moran','Moriarty','Morrissey','Morrow','Moylan','Mulcahy','Mulgrew','Mulhearn',
    'Mulhern','Mullally','Mullarkey','Mullen','Mulligan','Mullin','Mulroney','Murdoch','Murphy','Murray','Murtagh',
    'Nally','Naughton','Navin','Nestor','Nevin','Ní Arailt','Ní Chianáin','Ní Thomhnair','Ní Thomhnra','Ní Thomhrair',
    'Ní Thormaigh','Ní Tormadha','Nic Alasdair','Nic Alastair','Nic Alastruim','Nic Alsandair','Nic Amhalaí',
    'Nic Amhalaidh','Nic Amhalghadha','Nic Amhalghaidh','Nic Amhlaoibh','Nic Coitir','Nic Íomhair','Nic Oitir',
    'Nic Ospaic','Nic Raghnaill','Nic Rághnaill','Nic Raonaill','Nic Shitric','Nic Somhairle','NicLeóid',
    'Nig Amhalghadha','Nig Amhalghaidh','Nig Íomhair','Nig Shitric','Nolan','Noonan','Nunan',
    'Ó an Cháintighe','Ó Begléighinn','Ó Brádaigh','Ó Breisleáin','Ó Brolaigh','Ó Buadhaigh','Ó Cadhla','Ó Caiside',
    'Ó Cárthaigh','Ó Catháin','Ó Ceallacháin','Ó Chlúmháin','Ó Cianáin','Ó Ciardha','Ó Cillín','Ó Cíonga',
    'Ó Cléirigh','Ó Cobhthaigh','Ó Coileáin','Ó Conghalaigh','Ó Cormacáin','Ó Corráin','Ó Creachmhaoil',
    'Ó Cuindlis','Ó Curnín','Ó Daimhín','Ó Deargáin','Ó Domhnalláin','Ó Droighneáin','Ó Dubhagáinn','Ó Fearghuis',
    'Ó Fiaich','Ó Flaithbheartaigh','Ó Frighil','Ó Gadhra','Ó Gnímh','Ó Gráda','Ó hÁdhmaill','Ó hAichir',
    'Ó hAnluain','Ó hAnnáin','Ó hAodha','Ó hAonghusa','Ó hArailt','Ó hEidirsceóil','Ó hEochaidh','Ó hEodhasa',
    'Ó hÍceadha','Ó hUiginn','Ó Lachlainn','Ó Lachtnáin','Ó Laighin','Ó Lochlainn','Ó Lorcáin','Ó Maoilriain',
    'Ó Maol Fábhail','Ó Maoláin','Ó Maolconaire','Ó Maolmhuaidh','Ó Meadhra','Ó Midhir','Ó Rothláin','Ó Sé',
    'Ó Seachnasaigh','Ó Siadhail','Ó Tomhnair','Ó Tomhnra','Ó Tomhrair','Ó Tormadha','Ó Tormaigh','Ó Troighthigh',
    'O\'Boyle','O\'Brian','O\'Brien','O\'Callaghan','O\'Casey','O\'Connell','O\'Connor','O\'Conor','O\'Day',
    'O\'Dea','O\'Doherty','O\'Doherty family','O\'Donnell','O\'Donnell dynasty','O\'Donoghue','O\'Donohue',
    'O\'Donovan','O\'Dwyer','O\'Flaherty','O\'Fogartaigh','O\'Hagan','O\'Halloran','O\'Hara','O\'Hare','O\'Hea',
    'O\'Higgins','O\'Keefe','O\'Keeffe','O\'Kelly','O\'Lawlor','O\'Loughlin','O\'Neill','O\'Rahilly','O\'Reilly',
    'O\'Shaughnessey','O\'Shaughnessy','O\'Shea','O\'Sheehan','O\'Sullivan','O\'Toole family','Ormond',
    'Paterson','Patrick','Patten','Peters','Petty-Fitzmaurice','Philbin','Pierce',
    'Quigley','Quinlivan','Quinn',
    'Rabbitte','Rafferty','Raftery','Reagan','Redmond','Regan','Reilly','Reynolds','Riley','Riordan','Roche',
    'Rogan','Rooney','Rowan','Rowlan','Ruddy','Ryan',
    'Savage','Scanlan','Scottish names in Ulster','Scully','Shanahan','Shanley','Shannon','Sharkey','Sheehan',
    'Sheehy','Sheeran','Sheridan','Shirkey','Slattery','Spillane','Sugrue','Sweeney',
    'Tierney','Tobin','Togher','Tully','Twomey',
    'Uí Arailt','Uí Thomhnair','Uí Thomhnra','Uí Thomhrair','Uí Thormadha','Uí Thormaigh',
    'Walsh','Welch','Welsh','Whelan','Whelihan','White'
]

var irish_names_unisex = [
    'Carling','Casey','Cassidy','Flann','Kelly','Kerry','Lynn','Morgan',
    'Quinn','Rory','Rowan','Ryan','Shane','Shannon','Sláine'
]
