// Korean
var common_korean_names_male = [
    'Na-moo','Dal','Mit-eum','Beo-deul','Bitgaram',
    'Saem','Han-gyeol','Han-gil','Him-chan','Kang-min',
    'Kyung-gu','Kyung-mo','Kyung-taek','Kwang-jo','Nam-kyu',
    'Deok-su','Dong-gun','Mu-yeol','Mu-young','Byung-hun',
    'Seong-han','Seung-heon','Oh-seong','Yo-han','Yi-soo',
    'Il-sung','Jae-beom','Jae-seop','Chul-soon','Chi-won',
    'Hyun-seung','Gun','Kwang','Woong','Chul',
    'Hyuk','Ho','Hoon','Ga-ram','Na-ra',
    'Noo-ri','Du-ri','Ba-ram','Sol','Seul-ki',
    'Woo-ri','Ha-neul','Ha-da','Ha-ru','Ha-yan',
    'Han-wool','Kyung-lim','Kyung-wan','Nam-sun',
    'Young-shin','Ja-kyung','Jae-gyu','Jae-shin','Jae-in',
    'Ji-hae','Sang','Seong','Eun','Jae',
    'Ji','Hyun'
  ];

var common_korean_names_female = [
    'Ga-eul','Gyeo-wool','Go-eun','Gu-reum','Kkot',
    'Na-rae','Na-ri','Na-bi','No-eul','Da-rae',
    'Da-som','Dal-rae','Ra-on','Ra-woom','Ma-eum',
    'Mi-rae','Ba-da','Byeol','Bom','Bo-da',
    'Bo-ra','Bo-ram','Bit-na','Bi',
    'Sa-rang','Sandara','Sae-ron','Sae-rom',
    'Sae-byeok','So-ra','So-ri','Ah-reum','Ah-ri',
    'Yeo-reum','Ah-rong','I-seul','Jo-eun','Cho-rong',
    'Ha-na','Ha-nui','Eun-byul','Eun-bi','Ga-young',
    'Na-young','Mi-ran','Min-seo','Sook-ja','Ae-jung',
    'Yeo-jin','Young-ae','Yu-ri','Eun-chae','Yi-kyung',
    'Jang-mi','Hye-rin','Hye-rim','Lin','Ga-ram',
    'Na-ra','Noo-ri','Du-ri','Ba-ram','Sol',
    'Seul-ki','Woo-ri','Ha-neul','Ha-da','Ha-ru',
    'Ha-yan','Han-wool','Kyung-lim','Kyung-wan','Nam-sun',
    'Young-shin','Ja-kyung','Jae-gyu','Jae-shin','Jae-in',
    'Ji-hae','Sang','Seong','Eun','Jae',
    'Ji','Hyun'
  ];

var korean_surnames = [
    'Ga', 'Kar', 'Gar', 'Kah', 'Gah', 'Ca', 'Cah', 'Car', 'Kar',
    'Gan', 'Gahn', 'Kahn','Gal', 'Karl', 'Garl', 'Gahl', 'Kahl', 'Cahl', 'Carl',
    'Gam', 'Kahm', 'Gahm', 'Cam','Gang', 'Kahng', 'Khang',
    'Gyeon', 'Kyun', 'Kyeon', 'Kyoun', 'Kyon',
    'Gyeong', 'Kyung', 'Kyoung', 'Kyeong', 'Kyong',
    'Gye', 'Kyeh', 'Kye', 'Kay', 'Kie', 'Kae', 'Gae',
    'Go', 'Koh', 'Goh', 'Kho', 'Gho', 'Kor', 'Co',
    'Gok', 'Kog', 'Gog', 'Cock','Gong', 'Kohng', 'Koung', 'Goung', 'Khong', 'Cong',
    'Gwak', 'Kwag', 'Kwack', 'Gwag', 'Koak', 'Kuark', 'Quack',
    'Gwan', 'Quan', 'Kuan', 'Guan','Gyo', 'Kyoh', 'Gyoh',
    'Gu', 'Koo', 'Goo', 'Kou', 'Kuh', 'Khoo', 'Khu',
    'Guk', 'Kook', 'Gook', 'Kug', 'Gug', 'Cook',
    'Gung', 'Koong', 'Kwoong','Gwok', 'Kwog', 'Gwog', 'Quock',
    'Gwon', 'Kwon', 'Kweon', 'Kwun','Geun', 'Keun', 'Kuen', 'Guen',
    'Geum', 'Keum', 'Kum', 'Gum', 'Guem', 'Kuem',
    'Gi', 'Kee', 'Key', 'Gee', 'Ky', 'Khee', 'Kie',
    'Gil', 'Gill', 'Khil', 'Keel', 'Kihl', 'Kiehl', 'Kill',
    'Gim', 'Ghim', 'Kym', 'Keem','Na','Ra', 'Nah', 'La', 'Rha', 'Rah', 'Paw',
    'Nan','Ran', 'Nahn', 'Rahn', 'Nhan', 'Rhan',
    'Nam', 'Nahm', 'Nham', 'Narm','Namgung', 'Namkung', 'Namgoong', 'Namkoong', 'Namkuhng', 'Namguhng',
    'Nang','Rang', 'Nahng', 'Lang','Nae', 'Nai', 'Nay', 'Nea','No',
    'Ro', 'Noh', 'Roh', 'Ro', 'Raw','Noe','Roe', 'Roi', 'Noi',
    'Da','Dan', 'Dahn', 'Than','Dam', 'Tham', 'Dham', 'Dahm', 'Tahm',
    'Dang', 'Tang', 'Dhang', 'Thang','Dae', 'Dai', 'Dea', 'Day', 'Tai', 'Tay', 'Tea',
    'Do', 'Doh', 'Toe', 'Doe', 'Toh','Dokgo', 'Dokko', 'Toko', 'Tokko', 'Dockko', 'Dogko', 'Togko', 'Doko',
    'Don', 'Dohn', 'Tohn','Dong', 'Tong', 'Dhong', 'Thong',
    'Dongbang', 'Tongpang', 'Dongpang', 'Tongbang','Du', 'Doo', 'Tu', 'Do', 'Dou', 'Tou', 'To', 'Too',
    'Deung','Deungjeong','Ra','Ran','Rang','Ryeo', 'Ryuh','Roh','Roe',
    'Ryu', 'Ryou', 'Rou', 'Ryoo', 'Yu', 'Yoo', 'You', 'Yuh',
    'Ree','Rim','Ma', 'Mah', 'Mar','Man', 'Mann', 'Mahn','Mangjeol', 'Mangjul', 'Mangjuhl', 'Mangjoul',
    'Mae', 'May', 'Mea', 'Mai','Maeng', 'Maing', 'Meang',
    'Myeong', 'Myung', 'Myoung', 'Myong','Mo', 'Moh', 'Moe',
    'Mok', 'Mock', 'Mog', 'Mork','Myo', 'Myoh', 'Mio','Moo','Moobon',
    'Muk', 'Mook','Mun', 'Moon', 'Muhn','Mi', 'Mee', 'Mih', 'Meeh',
    'Min', 'Minn', 'Mihn','Bak', 'Park', 'Back', 'Bahk', 'Pahk',
    'Ban', 'Bahn', 'Pan', 'Pahn', 'Bhan', 'Van','Bang', 'Bhang', 'Bahng', 'Pahng', 'Phang',
    'Bae', 'Bai', 'Bea', 'Pae', 'Pai', 'Bay', 'Pay',
    'Baek', 'Baik', 'Back', 'Paik', 'Pack', 'Beak',
    'Beon','Beom', 'Bum', 'Bom', 'Peom', 'Pum', 'Puhm', 'Buhm',
    'Byeon', 'Byun', 'Byon', 'Pyun', 'Byoun', 'Pyon', 'Pyoun', 'Pyeon',
    'Bo', 'Boh', 'Poh','Bok', 'Pock', 'Bog', 'Pog', 'Bock',
    'Bong', 'Bhong', 'Bohng', 'Pohng', 'Vong',
    'Bu', 'Boo', 'Pu', 'Bou', 'Poo', 'Booh', 'Buh', 'Pou', 'Pooh',
    'Bi', 'Bee', 'Pee', 'Bih', 'Bhi', 'Pih', 'Phi',
    'Bin', 'Been', 'Pihn', 'Phin', 'Bean', 'Bihn', 'Pean',
    'Bing','Sa', 'Sah', 'Sar','Sagong', 'Sakong', 'Sagoung', 'Sakoung',
    'San', 'Sahn', 'Sarn','Sam', 'Sahm', 'Sarm','Sang', 'Sahng',
    'Seo', 'Suh', 'Surh', 'Su', 'Sur', 'So', 'Seoh',
    'Seomun', 'Suhmun', 'Suhmoon', 'Seomoon', 'Somoon',
    'Seok', 'Suk', 'Sok', 'Suck', 'Sek','Seon', 'Sun', 'Son', 'Suhn', 'Sen',
    'Seonu', 'Sunwoo', 'Seonwoo', 'Sonu', 'Sunoo', 'Sunwou', 'Seonwu', 'Sonwu',
    'Seol', 'Sul', 'Seul', 'Sol', 'Sull','Seob', 'Subb', 'Sup', 'Seop',
    'Seong', 'Sung', 'Soung', 'Song','So', 'Soh', 'Sou', 'Sow',
    'Son', 'Sohn', 'Soun','Song', 'Soung','Su', 'Soo', 'Sooh','Sun', 'Soon',
    'Seung', 'Sung','Si', 'Shi', 'See', 'Sie', 'Sea', 'Shee',
    'Sin', 'Shin', 'Shinn', 'Sheen', 'Seen', 'Sinn', 'Cynn',
    'Sim', 'Shim', 'Seem', 'Sheem', 'Sihm','A', 'Ah', 'Ar',
    'An', 'Ahn', 'Arn', 'Aan','Ae', 'Ay', 'Ai', 'Ea',
    'Ya', 'Yah', 'Yar','Yang','Ryang', 'Ryang', 'Lyang','Eo', 'Uh', 'Urh', 'Eoh',
    'Eogeum', 'Eokeum', 'Okeum', 'Okum', 'Ukeum', 'Ugeum', 'Ukum', 'Uhgeum', 'Uhkuem',
    'Eom', 'Um', 'Uhm', 'Oum', 'Ohm','Yeo','Ryeo', 'Yu', 'Yo', 'Yeu', 'Yuh', 'Yeo', 'Yoh',
    'Yeon','Ryeon', 'Youn', 'Yun', 'Yon', 'Yeun', 'Yeoun', 'Yuhn',
    'Yeom','Ryeom', 'Yum', 'Youm', 'Yeum', 'Yom', 'Yeoum',
    'Yeop', 'Yeob', 'Youb', 'Yeop', 'Yub', 'Yup', 'Yob',
    'Yeong', 'Young', 'Yung','Ye', 'Yeh','O', 'Oh', 'Oe', 'Au', 'Ou',
    'Ok', 'Ock', 'Ohk', 'Oak', 'Og', 'Ohg', 'Oag',
    'On', 'Ohn', 'Ohnn','Ong', 'Ohng', 'Oung',
    'Wan','Wang','Yo', 'You','Yong','Ryong', 'Ryong', 'Lyong','U', 'Woo', 'Wu', 'Ou', 'Wo', 'Uh',
    'Un', 'Woon', 'Wun', 'Whun', 'Wuhn','Won', 'Weon', 'Woen', 'Wone', 'Wun', 'One',
    'Wi', 'Wee', 'We', 'Wie','Yu','Ryu', 'Yoo', 'You','Yuk',
    'Ryuk', 'Yook', 'Youk', 'Yug', 'Ryuk', 'Yuck',
    'Yun', 'Yoon', 'Youn', 'Yune', 'Yeun','Eun', 'Un', 'Unn',
    'Eum', 'Um', 'Em', 'Yeum', 'Uem','I','Ri', 'Lee', 'Yi', 'Rhee', 'Ree', 'Rie', 'Rhie',
    'In', 'Ihn', 'Yin', 'Inn', 'Lin', 'Ean','Im',
    'Rim', 'Lim', 'Yim', 'Rim', 'Leem', 'Rhim', 'Eam','Ja',
    'Jang', 'Chang', 'Jahng', 'Jhang', 'Zang','Jeon', 'Jun', 'Chun', 'Chon', 'Cheon',
    'Jeom','Jeong', 'Chung', 'Jung', 'Joung', 'Chong', 'Cheong', 'Choung',
    'Je', 'Jae', 'Jea', 'Che', 'Jei', 'Jhe',
    'Jegal', 'Jaegal', 'Jekal', 'Jeagal', 'Jikal', 'Chegal', 'Chekal',
    'Jo', 'Cho', 'Joe', 'Joh', 'Jou','Jong', 'Chong','Jwa', 'Chwa', 'Joa', 'Choa',
    'Ju', 'Joo', 'Chu', 'Choo', 'Chow', 'Jou', 'Zoo', 'Jew', 'Zu',
    'Jeung', 'Jung', 'Cheung', 'Chung','Ji', 'Jee', 'Gi', 'Chee', 'Gee', 'Jhi',
    'Jin', 'Chin', 'Jeen', 'Gin','Cha', 'Char', 'Chah','Chang', 'Chahng',
    'Chae', 'Chai', 'Che', 'Chea','Cheon', 'Chun', 'Chon', 'Choun',
    'Cho', 'Chu', 'Chou', 'Choh','Choe', 'Choi', 'Che', 'Choy', 'Chwe', 'Chey',
    'Chu', 'Choo', 'Chou', 'Chyu','Tak', 'Tark', 'Tag', 'Tack', 'Tahk',
    'Tan', 'Tahn', 'Tann','Tae', 'Tai', 'Tay', 'Tea',
    'Pan', 'Pahn', 'Phan', 'Parn', 'Pann','Paeng', 'Pang', 'Paing', 'Peng', 'Peang',
    'Pyeon', 'Pyun', 'Pyon', 'Pyoun', 'Pyen','Pyeong', 'Pyung', 'Pyong', 'Pyoung', 'Pyeng',
    'Po', 'Pho', 'Poh','Pyo', 'Phyo', 'Pio', 'Peo', 'Pyoh', 'Pyou',
    'Pung', 'Poong', 'Puhng', 'Poohng','Pi', 'Pee', 'Phee', 'Phi', 'Phy', 'Pih',
    'Pil', 'Phil', 'Peel','Ha', 'Hah', 'Har','Hak', 'Hag', 'Hahk', 'Hahg', 'Hack',
    'Han', 'Hahn', 'Hann', 'Hanh','Ham', 'Hahm', 'Hamm', 'Haam','Hae', 'Hay', 'Hai', 'Hea',
    'Heo', 'Hur', 'Huh', 'Her', 'Hu', 'Ho', 'Hoh', 'Heoh','Hyeon', 'Hyun', 'Hyon', 'Hyoun',
    'Hyeong', 'Hyung', 'Hyoung', 'Hyong', 'Hyeung','Ho', 'Hoh',
    'Hong', 'Houng','Hwa', 'Howa', 'Hoa', 'Wha','Hwang', 'Whang',
    'Hwangmok', 'Whangmock', 'Wangmok','Hwangbo', 'Hwangpo', 'Whangpoh',
    'Hu', 'Hoo', 'Hooh', 'Huh'
];

var korean_full_given_list = [
    'Dong-geun','Nam-gi','Ki-nam','Kyung-min','Kwang-min','Da-bin','Kyung-seok','Kwang-seok','Dong-suk','Kyung-sun','Kwang-seon','Nam-seon','Dae-sung','Kyung-soo',
    'Kwang-su','Dong-soo','Kyung-sook','Kwang-sik','Kyung-ah','Do-yeon','Ki-young','Kyung-ok','Ki-woo','Dong-woo','Dong-wook','Ki-woong','Kyung-won','Kyu-won',
    'Dae-won','Do-won','Dong-won','Nam-il','Dong-il','Kyung-ja','Kyung-jae','Ki-jung','Kyung-ju','Dong-joo','Kyung-joon','Dong-jun','Kyung-chul','Kyu-chul','Dong-chul',
    'Kyung-tae','Ki-tae','Ki-ha','Dong-ha','Kwang-hyok','Dong-hyuk','Kwang-hyun','Dae-hyun','Do-hyun','Dong-hyun','Kyung-ho','Kwang-ho','Kyung-hwa','Kyung-hwan',
    'Kwang-hwan','Kwang-hoon','Do-hun','Dong-hoon','Kyung-hee','Kwang-hee','Da-hee','Do-hee','Mi-kyung','Min-kyung','Bo-kyung','Min-ki','Man-seok','Min-seok','Beom-seok',
    'Mi-sun','Min-sun','Man-soo','Myung-soo','Moon-soo','Min-soo','Beom-soo','Myung-sook','Mi-sook','Man-sik','Moon-sik','Mina','Mi-yeon','Bo-yeon','Mi-young',
    'Min-young','Bo-young','Myung-ok','Myung-yong','Min-woo','Byung-woo','Byung-wook','Mi-ja','Min-jae','Mi-jung','Min-jung','Min-ju','Myung-jun','Min-jun',
    'Byung-joon','Min-ji','Min-chul','Byung-chul','Min-hyuk','Min-ho','Byung-ho','Myung-hwa','Myung-hwan','Myung-hoon','Byung-hoon','Man-hee','Myung-hee','Mi-hee',
    'Min-hee','Byung-hee','Seong-gyeong','Soo-kyung','Sung-keun','Soo-geun','Sung-ki','Seung-gi','Sung-nam','Sang-mi','Sun-mi','Sung-mi','Su-mi','Sung-min','Soo-min',
    'Seung-min','Bin','Se-bin','Su-bin','Sung-soo','Seung-soo','Sung-sook','Soo-ah','Seung-ah','Seo-yeon','Se-yeon','So-yeon','Soo-yeon','Si-yeon','Seung-yeon',
    'Sun-young','Se-young','So-young','Soo-young','Shin-young','Seon-ok','Sun-ok','Sung-yong','Seung-yong','Sang-woo','Sun-woo','Sung-woo','Si-woo','Seung-woo',
    'Sang-wook','Seo-yun','Se-yoon','Seung-yoon','Sang-won','Suk-won','Sung-won','So-won','Si-won','Seung-won','Sung-il','Sang-eun','Seung-eun','Seong-ja','Soon-ja',
    'Sung-jae','Seung-jae','Soo-jung','Seok-ju','Sang-jun','Seo-jun','Seung-jun','Su-ji','Sung-jin','Soo-jin','Sang-chul','Sung-chul','Seung-chul','Sung-ha','Sang-hyun',
    'Seo-hyeon','Sung-hyun','So-hyun','Soo-hyun','Seung-hyun','Shin-hye','Seok-ho','Sung-ho','Seung-ho','Sun-hwa','Seung-hwa','Seung-hwan','Sang-hoon','Seong-hoon',
    'Se-hun','Seung-hoon','Sun-hee','Sung-hee','So-hee','Soo-hee','Soon-hee','Seung-hee','Yoo-kyung','Eun-kyung','Young-geun','Young-gi','Yong-gi','Young-nam',
    'Yong-nam','Young-mi','Yumi','Eun-mi','Young-min','Yu-bin','Yeon-seok','Yoo-suk','Yun-seok','Woo-sung','Yoon-sung','Eun-sung','Young-su','In-soo','Eun-soo',
    'Young-sook','Yoon-sook','In-sook','Eun-sook','Young-sik','Won-sik','In-sik','Eun-ah','In-young','Eun-young','Yeong-ok','Won-yong','Yeon-woo','Young-wook',
    'Ye-won','Won-il','Ye-eun','Young-ja','Young-jae','Won-jae','Eun-jae','Yoo-jung','Yoon-jung','Eun-jung','Young-joo','Eun-ju','Young-jun','Ye-jun','Yong-joon',
    'Ye-ji','Eun-ji','Young-jin','Ye-jin','Woo-jin','Yu-jin','Eun-jin','Young-chul','Won-chul','Young-tae','Young-ha','Eun-ha','In-hye','Eun-hye','Young-ho',
    'Yong-ho','Won-ho','Yong-hwa','Young-hwan','Young-hoon','Yeon-hee','Young-hee','Yoon-hee','Eun-hee','Jae-kyung','Jae-geun','Joon-ki','Jung-nam','Jung-min','Ji-min',
    'Chang-min','Cheol-min','Jae-suk','Jong-seok','Jun-seok','Ji-seok','Jin-sun','Jae-sung','Jin-sung','Jung-soo','Jong-soo','Ji-su','Jin-soo','Chul-soo','Jung-sook',
    'Jung-sik','Jung-ah','Jina','Ji-yeon','Jun-young','Ji-young','Jin-young','Chae-young','Jong-ok','Jae-yong','Jae-woo','Jung-woo','Ji-woo','Jin-woo',
    'Chang-woo','Chul-woo','Jae-wook','Jin-wook','Jae-woong','Ji-woong','Jae-yoon','Ji-yoon','Jae-won','Jung-won','Joo-won','Ji-won','Chae-won','Jung-il','Jong-il',
    'Jae-eun','Jung-eun','Ji-eun','Jeong-ja','Chun-ja','Jin-joo','Jae-joon','Jae-jin','Jung-jin','Joon-tae','Ji-tae','Jun-ha','Ji-ha','Jae-hyuk','Jong-hyuk','Joon-hyuk',
    'Jin-hyuk','Jae-hyun','Jung-hyun','Jong-hyun','Joo-hyun','Ji-hyun','Ji-hye','Jae-ho','Jung-ho','Joon-ho','Ji-ho','Jin-ho','Chang-ho','Jung-hwa','Chun-hwa',
    'Jung-hwan','Joo-hwan','Ji-hwan','Jin-hwan','Jung-hoon','Jong-hoon','Ji-hun','Chang-hoon','Jae-hee','Jung-hee','Joon-hee','Jin-hee','Chun-hee','Hyun-kyung',
    'Hye-kyung','Hee-kyung','Hong-gi','Hyun-mi','Hye-mi','Tae-min','Hyung-min','Han-bin','Hye-bin','Tae-suk','Hyun-seok','Ha-sun','Hee-sun','Tae-sung','Hae-seong',
    'Ho-sung','Hye-sung','Hee-sung','Tae-soo','Hyun-soo','Hye-su','Hyun-sook','Hyun-sik','Hyun-a','Tae-yeon','Tae-young','Hye-young','Tae-yong','Tae-woo','Hyun-woo',
    'Tae-wook','Hyun-wook','Tae-woong','Ha-yoon','Tae-won','Hae-won','Hyung-won','Hye-won','Tae-il','Hae-il','Ha-eun','Hye-ja','Han-jae','Ho-jung','Hyun-jung',
    'Hye-jung','Hee-jung','Hae-joo','Hong-joo','Hyo-joo','Hyun-joo','Hyung-joo','Tae-joon','Ha-joon','Ho-jun','Hyun-jun','Hyung-joon','Hee-joon','Hae-jin',
    'Ho-jin','Hyo-jin','Hyun-jin','Hye-jin','Hee-jin','Hee-chul','Hyun-tae','Tae-hyun','Tae-ho','Tae-hee','Hyun-hee'
];

var korean_names_unisex = [
    'Bo-kyung','Bo-ram','Bo-yeon','Boa','Byung-hee',
    'Chang-min','Chun-hee',
    'Da-bin','Do-yeon','Dong-joo','Duri',
    'Eun-jae','Eun-sang','Eun-soo','Eun-sung',
    'Ha-neul','Ha-sun','Ha-yoon','Hae-jin','Hae-joo','Hae-won','Hee-jin','Hee-jung','Hee-kyung',
    'Hee-sun','Hee-sung','Ho-jung','Hong-joo','Hye-sung','Hyo-jin','Hyun-hee','Hyun-jin',
    'Hyun-joo','Hyun-jung','Hyun-kyung','Hyun-soo','Hyung-joo',
    'In-soo','In-young',
    'Ja-kyung','Jae-hee','Jae-in','Jae-kyung','Jae-shin','Jae-yoon','Jae-young','Jeong-hyo',
    'Ji-ha','Ji-hae','Ji-ho','Ji-hu','Ji-hyun','Ji-min','Ji-su','Ji-won','Ji-woo','Ji-yoon',
    'Jin-hee','Jin-ho','Jin-soo','Jin-sung','Jin-young','Jong-ok','Joo-hyun','Joo-won','Joon-hee',
    'Jung-eun','Jung-hee','Jung-hwa','Jung-hyun','Jung-min','Jung-won',
    'Kum-song','Kwang-hee','Kyu-won','Kyung-hee','Kyung-ju','Kyung-lim','Kyung-min','Kyung-sun',
    'Kyung-won',
    'Man-hee','Min-jae','Min-ju','Min-kyung','Min-soo','Min-sun','Min-young','Mu-young','Myung-hee',
    'Nam-seon','Nam-sun','Nuri',
    'Sang','Sang-eun','Se-bin','Se-yeon','Se-young','Seong-gyeong','Seong-han','Seul-ki','Seung-eun',
    'Seung-hee','Seung-hwa','Seung-hyun','Seung-min','Seung-yeon','Seung-yong','Shin-young','Si-won',
    'Soo-hee','Soo-hyun','Soo-jin','Soo-jung','Soo-kyung','Soo-min','Soo-yeon','Soo-young','Su-bin',
    'Su-ji','Sun-hee','Sun-woo','Sun-young','Sung-hee','Sung-hyun',
    'Tae-hee','Tae-hyun','Tae-won','Tae-yeon','Tae-young',
    'Yeon-hee','Yeon-woo','Yi-soo','Yong-hwa','Yoo-jung','Yoon-jung','Young-ha','Young-hee',
    'Young-jin','Young-joo','Young-nam','Young-shin','Young-soo','Yu-bin','Yu-jin','Yun-hyeong',
    'Yunseo'
]

// End of Korean
