var scottish_gaelic_names_female = [
    'Ailios','Ailis','Aimil','Aingealag','Anabla','Anna','Aoife',
    'Barabal','Baraball','Barabla','Bearnas','Beasag','Beathag','Beileag','Beitidh','Beitiris','Beitris',
    'Bhioctoria','Brighde','Brìghde','Brìde',
    'Cairistiòna','Cairistìne','Cairistìona','Caitir','Caitlin','Caitrìona','Calaminag','Catrìona','Ceana',
    'Ceit','Ceiteag','Ceitidh','Ciorsdan','Ciorstag','Ciorstaidh','Ciorstan','Cotrìona','Criosaidh','Curstag',
    'Curstaidh',
    'Deirdre','Deòiridh','Deònaidh','Dior-bhorgàil','Diorbhail','Dior-bhail','Dior-bhàil','Dìorbhail','Doileag',
    'Doilidh','Doirin','Dolag',
    'Ealasaid','Eamhair','Eilidh','Eimhir','Eiric','Eithrig','Eubh','Eubha','Èibhlin',
    'Fionnaghal','Fionnuala','Floireans','Flòraidh','Frangag',
    'Giorsail','Giorsal','Gormall','Gormlaith',
    'Isbeil','Iseabail','Iseabal',
    'Leagsaidh','Leitis','Lili','Liùsaidh','Lucrais','Lìosa',
    'Magaidh','Maighread','Mairead','Mairearad','Malamhìn','Malmhìn','Marsail','Marsaili','Marta','Milread',
    'Moibeal','Moire','Moireach','Muire','Muireall','Màili','Màiri','Mòr','Mòrag',
    'Niamh',
    'Oighrig','Olibhia',
    'Peanaidh','Peigi',
    'Raghnaid','Raodhailt','Raonaid','Raonaild','Rut',
    'Seasaidh','Seonag','Seònaid','Simeag','Siubhan','Siùbhan','Siùsaidh','Siùsan','Sorcha','Stineag','Sìle',
    'Sìleas','Sìlis','Sìne','Sìneag','Sìonag',
    'Teasag','Teàrlag',
    'Ùna','Una'
]

var scottish_gaelic_names_male = [
    'Adaidh','Adhamh','Àdhamh','Ailbeart','Ailean','Ailig','Ailpean','Ailpein','Aindrea','Aindreas','Alasdair',
    'Amhladh','Amhlaibh','Amhlaidh','Amhlaigh','Angaidh','Anndra','Anndrais','Aodh','Aodhàn','Aonghas',
    'Aonghus','Arailt','Artair','Artur','Asgall','Àaron',
    'Baltair','Bearnard','Beathan','Beistean','Benneit','Bhaltair','Bhatair','Brian',
    'Cailean','Calum','Caomhainn','Cathal','Ciaran','Cliamain','Coinneach','Còiseam','Colla','Colum','Cille',
    'Comhnall','Conall','Conn','Cormac','Cormag','Crìsdean','Cuithbeart',
    'Daibhidh','Dàibhidh','Daidh','Daniel','Deorsa','Deòrsa','Diarmad','Domhnall','Dòmhnall','Domhnull','Dòmhnull',
    'Donaidh','Donnchadh','Dubh','Dubh-shìth','Dubhghall','Dànaidh','Dùghall','Dùghlas',
    'Eachann','Eacharn','Eairdsidh','Ealar','Eanraig','Eanruig','Eideard','Eirdsidh','Ellair','Eoghann','Eòghann',
    'Eumann','Eòghan','Eòin','Eòsaph',
    'Faolan','Fearchar','Fearghas','Filib','Fionn','Fionnghall','Fionnghan','Fionnlagh','Frang','Frangan',
    'Frangean','Friseal',
    'Gill-easbuig','Gilleasbuig','Gill-Eathain','Gill-Eòin','Gill-Iosa, Gillìosa','Gille-Aindreis','Gille-Brìdhde',
    'Gille-Caluim','Gille-Crìosd','Gilleasbaig','Gillebeart','Gillebrìde','Goiridh','Goraidh','Grannd',
    'Greum','Griogair','Guaidre','Gòrdan',
    'Harailt','Horas','Hùisdean',
    'Iagan','Iain','Ianatan','Iomhair','Iomhar','Isaac','Iàcob','Iòna','Iòsaph',
    'Labhrainn','Labhruinn','Lachlann','Laomann','Luthais','Lùcas',
    'Maoilios','Maol-Chaluim','Maol-Domhnuich','Maol-Dòmhnuich','Maol-Iosa','Maol-Moire','Maoldònaich',
    'Maolmhuire','Maolruibh','Marc','Marcas','Martainn','Màrtainn','Mata','Micheil','Morgan','Muireach',
    'Munga','Mungan','Murchadh','Mànas','Mànus','Mìcheal','Mìcheil','Neacal','Neachdainn','Niall','Niallghus',
    'Oilbhreis','Oisean',
    'Padean','Padruig','Para','Peadair','Peadar','Peadaran','Peadrus','Prainnseas','Pàdair','Pàdraig','Pàdruig',
    'Pàl','Pàra','Pàrlan','Pòl',
    'Raghnall','Raibeart','Raonull','Ringean','Risteard','Rob','Roibeart','Ruairidh','Ruaridh','Ruaraidh','Ruiseart',
    'Ràild',
    'Sachairi','Samuel','Sandaidh','Seaghdh','Seathan','Seoc','Seocan','Seonaidh','Seoras','Seumas','Seòras',
    'Seòsaidh','Sgàire','Sim','Simidh','Solamh','Somhairle','Steaphan','Stiùbhard','Stiùbhart','Sìm','Sìomon',
    'Tadhg','Tamhas','Taog','Tasgall','Tearlach','Teàrlach','Tiobaid','Tomag','Tomaidh','Torcadall','Torcall',
    'Torcull','Tormod','Tormoid','Tàmhas','Tòmachan','Tòmas','Uailean','Ualan','Ualraig','Uarraig','Uilleachan',
    'Uilleam','Uisdean','Ùisdean'
]

var scottish_gaelic_surnames = [
    'Aileanach','Ailpeanach','Allanach','Ambarsan','Andarsan','Anndrasdan','Arasgain','Ariss',
    'Baran','Barrach','Beitean','Bhàsa','Bhodhsa','Blacach','Blàr','Blàrach','Bochanan','Boid', 'Bòid',
    'Bòideach','Bràigheach','Breac','Breathnach','Brothaigh','Bruis','Brùn','Brus','Buideach','Buidheach',
    'Buids','Buiseid',
    'Cailbhin','Caileanach','Caimbeul','Caimbeulach','Camran','Camshron','Camshronach','Cananach','Canonach',
    'Caoidheach','Caolaisdean','Catach','Catan','Catanach','Ceallach','Ceanadach','Ceannaideach','Cearrach',
    'Ceiteach','Ciar','Ciarach','Ciogach','Coineagan','Crannach','Criatharach','Cuimeanach','Cuimein','Cuimeineach',
    'Càidh','Cèamp','Cèampach','Còmhan','Creag, Creagach',
    'Dalais','Deòir','Deòireach','Dòmhnallach', 'Dòmhnullach','Druimeanach','Druimein','Druimeineach','Druiminn',
    'Dubh','Dubhach','Dùbhghlas','Dùghallach','Dùghlas','Dùghlasach','Dunaid','Dunaidh',
    'Eabarcrombaigh',
    'Fearghasdan','Fionnlasdan','Flimean','Foirbeis','Foirbeiseach','Flachnàn','Fòlais','Friseal','Frisealach',
    'Gall','Gallach','Geadais','Geadasach','Gearailteach','Gilios','GillAndrais','GillEasbaig','GillEasbuig',
    'GilleChriosd','GilleChrìost','Gill\'Iosa','Giobsan','Glas','Gobha','Grannd','Grannda','Granndach','Greum',
    'Greumach','Griogal','Griogalach','Griogarach','Guaire','Guinne','Gunnach','Gutraidh','Gòrdan','Gòrdanach',
    'Ìomharach',
    'Latharnach','Lathurna','Leamhanach','Leamhnach','Leòideach','Lobhdain','Loganach','Loudain','Lìos',
    'Lìosach','Lùtair',
    'Mac a\' Bhacstair', 'Mac a\' Bhacastair','Mac a\' Bhàird','Mac a\' Bhàirling','Mac a\' Bharain','Mac a\' Bhiataich',
    'Mac a\' Bhiocair','Mac a\' Bhreatannaich','Mac a\' Bhreatnaich','Mac a\' Bhruthainn','Mac a\' Chananaich',
    'Mac a\' Charraige','Mac a\' Chléirich','Mac a\' Chombaich','Mac a\' Chriathrair','Mac a\' Chrosain','Mac a\' Chruiteir',
    'Mac a\' Ghniomhaid','Mac a\' Ghobhainn','Mac a\' Ghoill','Mac a\' Ghreidheir','Mac a\' Ghreusaiche','Mac a\' Ghrùdair',
    'Mac a\' Leòra','Mac a\' Lìos','Mac a\' Mhaighstir','Mac a\' Mhaoilein','Mac a\' Mhaoir','Mac a\' Mhiadhaich',
    'Mac a\' Mhuilleir','Mac a\' Phearsain','Mac a\' Phì','Mac an Aba','Mac an Airgid','Mac an Deòir','Mac an Deòraidh',
    'Mac an Dorsair','Mac an Duibh','Mac an Fhigheadair','Mac an Fhilidh','Mac an Fhleisteir','Mac an Fhoirbhich',
    'Mac an Fhùcadair','Mac an Fhuibhir','Mac an Iasgair','Mac an Lamhaich', 'Mac an Làmhaich','Mac an Leighe',
    'Mac an Lèigh','Mac an Luaimh','Mac an Oighre','Mac an Ollaimh','Mac an Rìgh','Mac an Rothaich','Mac an Ruaidh',
    'Mac an Sporain','Mac an Tàilleir','Mac an Tòisich','Mac an t-Sagairt','Mac an t-Saoir','Mac an t-Sealgair',
    'Mac an t-Srònaich','Mac an Tuairneir','Mac an Uidhir','Mac Iain Bhallaich','Mac Iain Duibh','Mac Iain Ruaidh',
    'Mac Iain Uidhir','Mac na Carraige','Mac na Ceàrda','Mac na Ceàrdaich','Mac na Maoile','Mac O\' Dreain',
    'Mac O\' Seannaig','Mac\'Ill\'Anndrais','Mac\'IlleBhreac','Mac\'Ill\'Eathainn','Mac\'Ill\'Fhinnein','Mac\'Ill\'Fhinntain',
    'Mac\'Ill\'Fhionndaig','Mac\'Ill\'Iosa','Mac\'Ill\'Oig','Mac\'Ille na Brataich','Mac\'IlleBhàin','Mac\'IlleBhuidh',
    'Mac\'IlleChiar','Mac\'IlleDhuibh','Mac\'IlleMhìcheil','Mac\'IlleMhòire','Mac\'IlleNaoimh','Mac\'IlleRiabhaich',
    'Mac\'IlleRuaidh','Mac\'Uirigh','MacAbhra','MacAbhsalain','MacAdaidh,MacÀdaidh','MacAdhaimh,MacÀdhaimh',
    'MacÀidh','MacAididh','MacAilein','MacAilpein','MacAlasdair','MacAmbrais','MacAmhalghaidh','MacAmhlaidh',
    'MacAmhlaigh','MacAnndaidh','MacAnndra','MacAnndrais','MacAodhagain','MacAoidh','MacAoidhein','MacAomalain',
    'MacAonghais','MacAra','MacArtain','MacArtair','MacAsgaidh','MacAsgaill','MacAsgain','MacBeatha','MacBeathag',
    'MacBhàididh','MacBharrais','MacBhàtair','MacBheatha','MacBheathaig','MacBheathain','MacBhigein','MacBhiocair',
    'MacBhlàthain','MacBhradain','MacBhraonaigh','MacBhrìghdeinn','MacCàba','MacCaibe','MacCailein','MacCain',
    'MacCaisgein','MacCalmain','MacCaluim','MacCaog','MacCaoig','MacCardaidh','MacCarmaig','MacCathachaidh',
    'MacCathail','MacCathbhaidh','MacCathain','MacCathasaigh','MacCathbharra','MacCeallaig','MacCeallaigh',
    'MacCeallair','MacCearnaigh','MacCearraich','MacCeasain','MacChoinnich','MacCianain','MacCiarain','MacCiomalain',
    'MacCionadha','MacCinidh','MacClambroch','MacCnaimhin','MacCnusachainn','MacCodrum','MacCoinnich','MacCoinnigh',
    'MacColla','MacComhainn','MacConaill','MacConnain','MacCosgraigh','MacCorcadail','MacCormaig','MacCrain',
    'MacCreamhain','MacCriomain','MacCrithein','MacCrosain','MacCruimein','MacCrìsdein','MacCròin','MacCuaig',
    'MacCuidhein','MacCuilcein','MacCuinn','MacCuinnleis','MacCuirc','MacCuithein','MacCullach','MacCullaich',
    'MacCumasgaigh','MacCumhais','MacCuthais','MacCòiseam','MacCòmhain','MacCòmhghan','MacCùga','MacDheòrsa',
    'MacDhiarmaid','MacDhonnchaidh','MacDhrostain','MacDhubhaich','MacDhubhaig','MacDhubhShìth','MacDhubhthaich',
    'MacDhuibh','MacDhunlèibhe','MacDiarmaid','MacDhàibhidh','MacDhòmhnaill','MacDhùghaill','MacDhùnShléibhe',
    'MacEachaidh','MacEachainn','MacEachairn','MacEacharna','MacEalair','MacEalar','MacEamailinn','MacEanain',
    'MacEanraig, MacEanraig','MacEòghainn','MacFhearchair','MacFhearghail','MacFhearghais','MacFhilib',
    'MacFhiongain','MacFhionghain', 'MacFhionghuin','MacFhionnlaigh','MacFhitheachain','MacFhlaithbheartaich',
    'MacFhraing','MacFhraingein','MacFigeinn','MacFrìdeinn','MacFuirigh','MacGairbheith','MacGaradh','MacGhearailt',
    'MacGill-Eain','MacGhille','MacGill\'Earnain','MacGill\'Easbaig','MacGill\'Eòin','MacGill\'Fhaolagain',
    'MacGill\'Fhiontag','MacGill\'Oig','MacGill\'Onaidh','MacGille','MacGilleBhàin','MacGilleBhràth','MacGilleBhreac',
    'MacGilleBhrìghde','MacGilleChaluim','MacGilleChrìosd','MacGilleDhonaghart','MacGilleathain','MacGilleDhuibh',
    'MacGilleFhialain','MacGilleGhlais','MacGillIosa','MacGilleMhartainn','MacGilleRiabhaich','MacGilleSeathanaich',
    'MacGiobain','MacGlaisein','MacGoraidh','MacGobhainn','MacGoraidh','MacGriogair','MacGuaire','MacGumaraid',
    'MacIain','MacIllAnndrais','MacIllAodhagain','MacIllDheòra','MacIllEarnain','MacIllEasbaig','MacIllEathain',
    'MacIlleBhàin','MacIlleBheathain','MacIlleBhlàthain','MacIlleBhràth','MacIlleBhrìghde','MacIlleBhris',
    'MacIlleBhuidhe','MacIlleChaluim','MacIlleChatain','MacIlleChathbhaidh','MacIlleChiar','MacIlleChiarain',
    'MacIlleChomhghain','MacIlleChonaill','MacIlleChrìosd','MacIlleChruim','MacIlleDhòmhnaich','MacIlleDhonaghart',
    'MacIlleDhubhthaich','MacIlleDhuibh','MacIlleDhuinn','MacIlleGhlais','MacIlleGhuinnein','MacIlleGhuirm',
    'MacIll\'Éidich','MacIll\'Eòin','MacIlleMhaoil','MacIlleMhàrtainn','MacIlleMhearnaig','MacIlleMhìcheil',
    'MacIlleMhoire','MacIlleNaoimh','MacIllePhàdraig','MacIllePheadair','MacIlleRiabhaich','MacIlleRuaidh',
    'MacIlleSheathain','MacIlleSheathanaich','MacIlleSheathnaich','MacIlleThòmhais','MacIllFhaolagain',
    'MacIll\'Fhaolain','MacIllFheargain','MacIll\'Fhialain','MacIll\'Fhinnein','MacIll\'Fhionndaig','MacIllFhionndain',
    'MacIllIanain','MacIllÌmheir','MacIllIomchadha','MacIllÌosa','MacIllOnchon','MacIllOnfhaidh','MacIll\'osa',
    'MacIllUidhir','MacIomhair,MacÌomhair','MacIonmhainn','MacIosaig,MacÌosaig','MacLabhrainn','MacLabhruinn',
    'MacLachlainn','MacLagain','MacLamraich','MacLaomainn','MacLathagain','MacLeòid','MacLeòir','MacLianain',
    'MacLothaidh','MacLiuthar','MacLughaidh','MacLuinge','MacLuirg','MacLulaich','MacLùcaidh','MacLùcais',
    'MacMhaighstir','MacMhanachain','MacMhannain','MacMhaoilein','MacMhaoirn','MacMhaolagain','MacMhaolain',
    'MacMhaolBheatha','MacMhaolChaluim','MacMhaolDòmhnaich','MacMhaolÌosa','MacMharais','MacMharcais','MacMhata',
    'MacMhatha','MacMhathain','MacMhàrtainn','MacMhànais','MacMhèinn','MacMhiadhchain','MacMhìcheil','MacMhoirein',
    'MacMhòrdha','MacMhorgain','MacMhuircheartaich','MacMhuirich','MacMhunna','MacMhurardaich','MacMhurchaidh',
    'MacNaois','MacNaomhain','MacNeacail','MacNeachdain','MacNeis','MacNèill','MacNia','MacNiallghais','MacNiallghuis',
    'MacNìll','MacNiocail','MacNobaill','MacPhaid','MacPhaidein','MacPhail,MacPhàil','MacPhairce','MacPhàdraig',
    'MacPhàic','MacPhàidein','MacPhàil','MacPhàrlain','MacPheadair','MacPheadarain','MacPheadrais','MacPheidearain',
    'MacPhilip','MacPhòil','MacRabaidh','MacRaghnaill','MacRaibeirt','MacRaoimhin','MacRaoiridh','MacRaonaill',
    'MacRath','MacRàild','MacRiada','MacRiocaird','MacRisnidh','MacRìdeinn','MacRìgh','MacRob','MacRobaidh',
    'MacRoibeirt','MacRoithridh','MacRuairidh','MacRusachainn','MacShanndaidh','MacShealbhaigh','MacSheòrais',
    'MacSheòrsa','MacShimidh','MacShithich','MacShitrig','MacShìm','MacShomhairle','MacShuibhne','MacSiridh',
    'MacSporain','MacSuain','MacSual','MacThaidhg','MacTheàrlaich','MacThom','MacThomaidh','MacThorcadail',
    'MacThorcaill','MacThàmhais','MacThòmais','MacTiridh','MacTuirc','MacUalraig','MacUaraig','MacUchtraigh',
    'MacUilleim','MacUirigh','MacUisdein','MacUrardaidh','MacUrardaigh','MacUrchadain','MacUrchaidh','MacUsbaig',
    'MacÙisdein','Maoileanach, Maolanach','MaolIosa','Matasan','Mathanach','Matharnach','Mawr', 'Maor','Moireach',
    'Moireasdan','Moireasdanach','Morgan','Morganach','Munna','Màrnach','Màrr','Màrtainn','Mèinn','Mèinnearach',
    'Niocalsan',
    'O\' Brolchain','O\' Cain','O\' Luingeachain',
    'Padarsan','Paorach','Peadarsan','Peucag','Peutan','Preas','Puidreach',
    'Rathais','Robasan','Robasdan','Roid','Roideach','Ros','Ròs','Rosach','Ròsach','Rothach','Ruadh','Ruiseal',
    'Sailcirc','Salmond','Seadh','Seadhg','Seagha','Seaghach','Seathanach','Sgèin','Sginnearach','Sgot','Singleir',
    'Siosal','Siosalach','Smios','Stiùbhart','Stiùbhartach','Sùdrach','Sutharlainn','Sutharlan','Suthurlanach',
    'Tod','Todt','Talmhach','Tolmach','Tuairnear','Tàileach','Tàillear','Tulach',
    'Ualas','Umphraidh','Urchadainn','Urchardan'
]

var scottish_gaelic_names_unisex = [
    'Kennedy','Rory'
]
